name: Django CI/CD Pipeline

on:
  push:
    branches:
      - budgeting-backend  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}
        SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: ./budgeting_backend
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Database Migrations
        working-directory: ./budgeting_backend
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: SSH into EC2 & Deploy
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          echo "$EC2_SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            cd ~/home/ubuntu/budgeting-proj/budgeting-proj/budgeting_backend 
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
          EOF
